before_install:
  - sudo echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" >> /etc/apt/sources.list.d/llvm.list
  - sudo echo "deb-src http://llvm.org/apt/precise/ llvm-toolchain-precise main" >> /etc/apt/sources.list.d/llvm.list
  - sudo apt-get update
install:
  - sudo apt-get install trousers libtspi-dev
  - sudo apt-get install cmake 
  - sudo apt-get install libcrypto++9 libcrypto++9-dbg libcrypto++-dev
  - sudo apt-get install libblkid-dev
  - sudo apt-get install clang-3.3
language: cpp
script: make
compiler:
  - clang
  - gcc
before_script:
  - cd bin
  - cmake ../
