before_install:
  - sudo apt-get update
install:
  - sudo apt-get install trousers libtspi-dev
  - sudo apt-get install cmake 
  - sudo apt-get install libcrypto++ libcrypto++-dbg libcrypto++-dev
  - sudo apt-get install libblkid-dev
language: cpp
script: make
compiler:
  - clang
  - gcc
before_script:
  - cd bin
  - cmake ../
